version: "3"
services:
  riscv-assembly:
    build: .
    volumes: 
      - ./:/work
    command: >
      riscv64-unknown-elf-gcc
      -S
      -march=rv32i
      -mabi=ilp32
      -o /work/hello.s
      /work/hello.c
  riscv-assembly:
    build: .
    volumes: 
      - ./:/work
    command: >
      riscv64-unknown-elf-gcc
      -march=rv32i
      -mabi=ilp32
      -o /work/hello.o
      /work/hello.c
    depends_on: 
      - riscv-assembly